name: frontend
description: Smart Complaint System Flutter App

publish_to: 'none'

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
